### ISSUE TITLE
A few issues with README:

### ISSUE THREAD

**Issue by Avivhdr** [davestewart/todo-emojis#5]
1. Hyperlink on `png` is broken.
2. looks like there is the README isn't updated or the link to the zip file points to an older version:
  2.1. The `emoji` folder doesn't contain the `todo_pause` png.
  2.2 There is no `high` folder.
  
![image](https://user-images.githubusercontent.com/23265867/157023864-de4921bd-10c9-41dc-903b-03da4e2f5eee.png)

**Comment by davestewart** [comment]
Thanks! I'll get on it

**Comment by Avivhdr** [comment]
https://github.com/davestewart/todo-emojis/pull/6

**Comment by davestewart** [comment]
Closed by #6
